name: diabetes-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - joblib
      - optuna
      - mlflow
      - dagshub
